name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Enable Nightly Rust Toolchain
      run: rustup toolchain install nightly
    - name: Add PowerPC toolchain
      run: rustup target add --toolchain nightly powerpc-unknown-linux-gnu
    - name: NPM Install
      run: npm install
    - name: Build Linux App
      run: npm run electron:linux
